runtime: python38
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /data/(.*)
  static_files: dist/data/\1
  upload: dist/data/(.*)
  secure: always

- url: /helpers
  static_dir: dist/helpers
  secure: always

- url: /images/(.*)
  static_files: dist/images/\1
  upload: dist/images/(.*)
  secure: always
  expiration: "365d"

- url: /node_modules
  static_dir: dist/node_modules
  secure: always

- url: /src
  static_dir: dist/src
  secure: always
  expiration: "365d"

- url: /robots.txt
  static_files: dist/robots.txt
  upload: dist/robots.txt
  secure: always

- url: /sitemap.xml
  static_files: dist/data/sitemap.xml
  upload: dist/data/sitemap.xml
  secure: always

- url: /blog/index.xml
  static_files: dist/data/blog/index.xml
  upload: dist/data/blog/index.xml
  secure: always

- url: /favicon.ico
  static_files: dist/favicon.ico
  upload: dist/favicon.ico

- url: /service-worker.js
  static_files: dist/service-worker.js
  upload: dist/service-worker.js
  secure: always
  expiration: "0d 0h"

- url: /service-worker.js.map
  static_files: dist/service-worker.js.map
  upload: dist/service-worker.js.map
  secure: always
  expiration: "0d 0h"

- url: /manifest.json
  static_files: dist/app.webmanifest
  upload: dist/app.webmanifest
  secure: always
  expiration: "30d"

- url: /app.webmanifest
  static_files: dist/app.webmanifest
  upload: dist/app.webmanifest
  secure: always
  expiration: "30d"

- url: .*
  secure: always
  script: auto
