name: Test-Deploy-PR

on: [push]

jobs:
  build:
    name: Build Data and PWA
    runs-on: ubuntu-latest
    steps:
      - name: Install System Deps
        run: sudo apt install make jq zsh sed
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: '0.59.1'
      - name: Run `make build`
        run: make build-ci
  deploy:
    name: Deploy to GAE
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GAE_PID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GAE_CREDENTIALS }}
        with:
          args: app deploy ${GITHUB_WORKSPACE}/ship/app.yaml --no-promote --version ${GITHUB_SHA::8}
