name: Test-Deploy-PR

on: [push]

jobs:
  build:
    name: Build + Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install System Deps
        run: sudo apt install make jq zsh sed
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: '0.59.1'
      - name: Build PWA
        run: make build-ci
      - name: Deploy to Google App Engine
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GAE_PID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GAE_CREDENTIALS }}
        with:
          args: app deploy ${GITHUB_WORKSPACE}/ship/app.yaml --no-promote --version ${GITHUB_SHA};
  perf:
    name: Lighthouse Audits
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - run: mkdir /tmp/artifacts
      - name: Audit URLs with Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: /tmp/artifacts
          urls: https://${{ github.sha }}-dot-justinribeiro-web.appspot.com
      - name: Pass/Fail PR with Lighthouse results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "90"
          minBestPracticesScore: "90"
          minPerformanceScore: "90"
          minProgressiveWebAppScore: "90"
          minSeoScore: "90"
      - name: Save Lighthouse results
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-results
          path: /tmp/artifacts