name: Test-Deploy-PR

on: [push]

jobs:
  build:
    name: Build + Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install System Deps
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: '0.59.1'
        run: sudo apt install make jq zsh sed
      - name: Build PWA
        run: make build-ci
      - name: Deploy to Google App Engine
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GAE_PID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GAE_CREDENTIALS }}
        with:
          args: app deploy ${GITHUB_WORKSPACE}/ship/app.yaml --no-promote --version ${GITHUB_SHA};
  perf:
    name: Lighthouse Audits
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Audit URLs using Lighthouse and ensure performance budget
        uses: treosh/lighthouse-ci-action@v1
        with:
          url: https://${{ github.sha }}-dot-justinribeiro-web.appspot.com
      - name: Save results
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-results
          path: './results'